services:
  faker:
    build: ./faker
    volumes:
      - shared-data:/db

  backend:
    build: ./backend
    volumes:
      - shared-data:/db
    depends_on:
      faker:
        condition: service_completed_successfully

  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:8501:8501"
    depends_on:
      backend:
        condition: service_started

volumes:
  shared-data:
