name: "CodiumAI PR Agent"

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:

jobs:
  pr_agent:
    if: ${{ github.event.sender.type != 'Bot' && !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run CodiumAI PR agent
    steps:
      - name: PR Agent action step
        uses: Codium-ai/pr-agent@v0.21
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
